### ISSUE TITLE
Positional Encoding

### ISSUE THREAD

**Issue by collinarnett** [alextrevithick/GRF#3]
I'm using the positional encoder found in the NERF paper to encode my images after stacking the view points on the colors as mentioned in the paper however I'm unable to get the shapes to line up for input into the CNN. In NERF's implementation they flatten before sending their inputs to encoder.

To give a more concrete example of what I'm talking about here is my code
```python
# reshape inputs to [20, 378, 504, 6] concatenating view to colorspace
inputs = torch.tensor(np.concatenate([images, np.broadcast_to(np.expand_dims(C, (1,2)), images.shape)], axis=-1))
# create embedder with length 5 as specified in the paper
embed, input_ch = get_embedder(5, 0)
# flatten. not sure if this step is required shape of [3810240, 6]
inputs_flat = torch.reshape(inputs, [-1, inputs.shape[-1]])
# apply embedding for a output shape of  [3810240, 66]
embedding = embed(inputs)
```
Not really sure where to go from here to submit to the CNN.

**Comment by alextrevithick** [comment]
Thanks for your interest in our work! The code is coming soon...

In terms of your specific query, it seems that you are trying to append all the points being classified, which is intractable. To avoid this, we stack only the viewpoint corresponding to each view to all of the pixels. So, it seems you have 20 views to push through the CNN module. Thus, get the fourth column of the pose for each of those input views, and stack that same viewpoint to all RGBs for that input image. Note that you should apply the embedding before stacking, but for simplicity here, I didn't. 


```
# poses has shape [20,4,4]
viewpoints = poses[:,:3,-1] # now shape [20,3]
# now concatenate viewpoints to tensor for input to CNN (call it RGBs) with shape [20,H,W,3]
viewpoints = np.broadcast_to(viewpoints[:,None,None], [20, H,W, 3])
input_CNN = np.concatenate([rgbs, viewpoints], -1)
```

There seem to be more elegant ways to encode the relative position of points in space to the camera, including working in a camera-centered coordinate system, but in our paper we keep everything in world space. 

Let me know if that helps.

**Comment by collinarnett** [comment]
Is the code still coming soon? Just checking in.
